import subprocess
import os
from SCons.Script import Import

Import("env")

def get_firmware_version():
    try:
        version = subprocess.check_output(
            ["git", "describe", "--tags", "--always", "--dirty"],
            cwd=env["PROJECT_DIR"],
            stderr=subprocess.DEVNULL
        ).strip().decode("utf-8")
    except Exception:
        version = "unknown"
    return version

# Generate immediately at script load time so the file exists before compilation
version = get_firmware_version()
header_path = os.path.join(env["PROJECT_DIR"], "src", "version.h")

content = f"""\
#pragma once
// Auto-generated by generate_version.py – do not edit manually

#define FIRMWARE_VERSION "{version}"
"""

# Only write if content has changed (avoids triggering unnecessary rebuilds)
if os.path.exists(header_path):
    with open(header_path, "r") as f:
        if f.read() == content:
            print(f"ℹ️  version.h unchanged ({version})")
        else:
            with open(header_path, "w") as f:
                f.write(content)
            print(f"✅ version.h updated: {version}")
else:
    with open(header_path, "w") as f:
        f.write(content)
    print(f"✅ version.h generated: {version}")
