// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: RemoteControl

#ifndef _REMOTECONTROL_UI_H
#define _REMOTECONTROL_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "ui_Central_Screen.h"
#include "ui_Basic_Settings_Screen.h"
#include "ui_No_Connection_Screen.h"
#include "ui_Cards_Screen.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_icons_icon_next_png);    // assets/icons_icon_next.png
LV_IMG_DECLARE(ui_img_icons_icon_prev_png);    // assets/icons_icon_prev.png
LV_IMG_DECLARE(ui_img_icons_icon_home_png);    // assets/icons_icon_home.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
