// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: RemoteControl

#include "ui.h"

lv_obj_t * ui_Basic_Settings_Screen = NULL;
lv_obj_t * ui_Container1 = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_Button2 = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_Button3 = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_ImgButton1 = NULL;
lv_obj_t * ui_ImgButton6 = NULL;
// event funtions
void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        OnCycleWeaponClicked(e);
    }
}

void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        OnCycleMatchTypeClicked(e);
    }
}

void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        OnCycleIntensityClicked(e);
    }
}

void ui_event_ImgButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Central_Screen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Central_Screen_screen_init);
    }
}

void ui_event_ImgButton6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SpecificSettingsScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_SpecificSettingsScreen_screen_init);
    }
}

// build funtions

void ui_Basic_Settings_Screen_screen_init(void)
{
    ui_Basic_Settings_Screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Basic_Settings_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container1 = lv_obj_create(ui_Basic_Settings_Screen);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, lv_pct(100));
    lv_obj_set_height(ui_Container1, lv_pct(100));
    lv_obj_set_x(ui_Container1, 20);
    lv_obj_set_y(ui_Container1, -10);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button1 = lv_btn_create(ui_Container1);
    lv_obj_set_width(ui_Button1, 200);
    lv_obj_set_height(ui_Button1, 50);
    lv_obj_set_x(ui_Button1, 10);
    lv_obj_set_y(ui_Button1, 30);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label8 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 19);
    lv_obj_set_y(ui_Label8, 0);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Cycle Weapon");

    ui_Button2 = lv_btn_create(ui_Container1);
    lv_obj_set_width(ui_Button2, 200);
    lv_obj_set_height(ui_Button2, 50);
    lv_obj_set_x(ui_Button2, 10);
    lv_obj_set_y(ui_Button2, 0);
    lv_obj_set_align(ui_Button2, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label9 = lv_label_create(ui_Button2);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "Cycle Match Type");

    ui_Button3 = lv_btn_create(ui_Container1);
    lv_obj_set_width(ui_Button3, 200);
    lv_obj_set_height(ui_Button3, 50);
    lv_obj_set_x(ui_Button3, 10);
    lv_obj_set_y(ui_Button3, 0);
    lv_obj_set_align(ui_Button3, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label10 = lv_label_create(ui_Button3);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 10);
    lv_obj_set_y(ui_Label10, 0);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "Cycle Intensity");

    ui_ImgButton1 = lv_imgbtn_create(ui_Container1);
    lv_imgbtn_set_src(ui_ImgButton1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_icons_icon_home_png, NULL);
    lv_obj_set_width(ui_ImgButton1, 40);
    lv_obj_set_height(ui_ImgButton1, 40);
    lv_obj_set_x(ui_ImgButton1, -15);
    lv_obj_set_y(ui_ImgButton1, 5);
    lv_obj_set_align(ui_ImgButton1, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_ImgButton1, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags

    ui_ImgButton6 = lv_imgbtn_create(ui_Basic_Settings_Screen);
    lv_imgbtn_set_src(ui_ImgButton6, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_icons_icon_next_png, NULL);
    lv_obj_set_width(ui_ImgButton6, 40);
    lv_obj_set_height(ui_ImgButton6, 40);
    lv_obj_set_x(ui_ImgButton6, -10);
    lv_obj_set_y(ui_ImgButton6, -10);
    lv_obj_set_align(ui_ImgButton6, LV_ALIGN_BOTTOM_RIGHT);

    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton1, ui_event_ImgButton1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton6, ui_event_ImgButton6, LV_EVENT_ALL, NULL);

}

void ui_Basic_Settings_Screen_screen_destroy(void)
{
    if(ui_Basic_Settings_Screen) lv_obj_del(ui_Basic_Settings_Screen);

    // NULL screen variables
    ui_Basic_Settings_Screen = NULL;
    ui_Container1 = NULL;
    ui_Button1 = NULL;
    ui_Label8 = NULL;
    ui_Button2 = NULL;
    ui_Label9 = NULL;
    ui_Button3 = NULL;
    ui_Label10 = NULL;
    ui_ImgButton1 = NULL;
    ui_ImgButton6 = NULL;

}
