// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: RemoteControl

#ifndef UI_BASIC_SETTINGS_SCREEN_H
#define UI_BASIC_SETTINGS_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Basic_Settings_Screen
extern void ui_Basic_Settings_Screen_screen_init(void);
extern void ui_Basic_Settings_Screen_screen_destroy(void);
extern lv_obj_t * ui_Basic_Settings_Screen;
extern lv_obj_t * ui_Container1;
extern void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label8;
extern void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label9;
extern void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label10;
extern void ui_event_ImgButton1(lv_event_t * e);
extern lv_obj_t * ui_ImgButton1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

