// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: RemoteControl

#include "ui.h"

lv_obj_t * ui_Color_Screen = NULL;
lv_obj_t * ui_ImgButton18 = NULL;
lv_obj_t * ui_Colorwheel1 = NULL;
// event funtions
void ui_event_ImgButton18(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Central_Screen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Central_Screen_screen_init);
    }
}

// build funtions

void ui_Color_Screen_screen_init(void)
{
    ui_Color_Screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Color_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButton18 = lv_imgbtn_create(ui_Color_Screen);
    lv_imgbtn_set_src(ui_ImgButton18, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_icons_icon_home_png, NULL);
    lv_obj_set_width(ui_ImgButton18, 40);
    lv_obj_set_height(ui_ImgButton18, 40);
    lv_obj_set_x(ui_ImgButton18, 2);
    lv_obj_set_y(ui_ImgButton18, -3);
    lv_obj_set_align(ui_ImgButton18, LV_ALIGN_BOTTOM_LEFT);

    ui_Colorwheel1 = lv_colorwheel_create(ui_Color_Screen, true);
    lv_obj_set_width(ui_Colorwheel1, 220);
    lv_obj_set_height(ui_Colorwheel1, 220);
    lv_obj_set_x(ui_Colorwheel1, -1);
    lv_obj_set_y(ui_Colorwheel1, -38);
    lv_obj_set_align(ui_Colorwheel1, LV_ALIGN_CENTER);
    lv_obj_set_style_arc_width(ui_Colorwheel1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Colorwheel1, 60, LV_PART_KNOB | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ImgButton18, ui_event_ImgButton18, LV_EVENT_ALL, NULL);

}

void ui_Color_Screen_screen_destroy(void)
{
    if(ui_Color_Screen) lv_obj_del(ui_Color_Screen);

    // NULL screen variables
    ui_Color_Screen = NULL;
    ui_ImgButton18 = NULL;
    ui_Colorwheel1 = NULL;

}
