// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: RemoteControl

#ifndef UI_CARDS_SCREEN_H
#define UI_CARDS_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Cards_Screen
extern void ui_Cards_Screen_screen_init(void);
extern void ui_Cards_Screen_screen_destroy(void);
extern lv_obj_t * ui_Cards_Screen;
extern void ui_event_ImgButton4(lv_event_t * e);
extern lv_obj_t * ui_ImgButton4;
extern lv_obj_t * ui_Container2;
extern void ui_event_ButtonYLeft(lv_event_t * e);
extern lv_obj_t * ui_ButtonYLeft;
extern lv_obj_t * ui_Label12;
extern void ui_event_ButtonRLeft(lv_event_t * e);
extern lv_obj_t * ui_ButtonRLeft;
extern lv_obj_t * ui_Label13;
extern void ui_event_ButtonBLeft(lv_event_t * e);
extern lv_obj_t * ui_ButtonBLeft;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Container3;
extern void ui_event_ButtonYRight(lv_event_t * e);
extern lv_obj_t * ui_ButtonYRight;
extern lv_obj_t * ui_Label15;
extern void ui_event_ButtonRRight(lv_event_t * e);
extern lv_obj_t * ui_ButtonRRight;
extern lv_obj_t * ui_Label16;
extern void ui_event_ButtonBRight(lv_event_t * e);
extern lv_obj_t * ui_ButtonBRight;
extern lv_obj_t * ui_Label17;
extern void ui_event_ButtonUW2F(lv_event_t * e);
extern lv_obj_t * ui_ButtonUW2F;
extern lv_obj_t * ui_Label18;
extern void ui_event_ButtonPRIO(lv_event_t * e);
extern lv_obj_t * ui_ButtonPRIO;
extern lv_obj_t * ui_Label19;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

