// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: RemoteControl

#include "ui.h"

lv_obj_t * ui_Cards_Screen = NULL;
lv_obj_t * ui_ImgButton4 = NULL;
lv_obj_t * ui_Container2 = NULL;
lv_obj_t * ui_ButtonYLeft = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_ButtonRLeft = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_ButtonBLeft = NULL;
lv_obj_t * ui_Label14 = NULL;
lv_obj_t * ui_Container3 = NULL;
lv_obj_t * ui_ButtonYRight = NULL;
lv_obj_t * ui_Label15 = NULL;
lv_obj_t * ui_ButtonRRight = NULL;
lv_obj_t * ui_Label16 = NULL;
lv_obj_t * ui_ButtonBRight = NULL;
lv_obj_t * ui_Label17 = NULL;
lv_obj_t * ui_ButtonUW2F = NULL;
lv_obj_t * ui_Label18 = NULL;
lv_obj_t * ui_ButtonPRIO = NULL;
lv_obj_t * ui_Label19 = NULL;
lv_obj_t * ui_ButtonUndoUW2FTimerReset = NULL;
lv_obj_t * ui_Label20 = NULL;
// event funtions
void ui_event_ImgButton4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Central_Screen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Central_Screen_screen_init);
    }
}

void ui_event_ButtonYLeft(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        OnYellowCardLeftClicked(e);
    }
    if(event_code == LV_EVENT_LONG_PRESSED) {
        OnYellowCardLeftLongPressed(e);
    }
}

void ui_event_ButtonRLeft(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        OnRedCardLeftClicked(e);
    }
    if(event_code == LV_EVENT_LONG_PRESSED) {
        OnRedCardLeftLongPressed(e);
    }
}

void ui_event_ButtonBLeft(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        OnBlackCardLeftClicked(e);
    }
    if(event_code == LV_EVENT_LONG_PRESSED) {
        OnBlackCardLeftLongPressed(e);
    }
}

void ui_event_ButtonYRight(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        OnYellowCardRightClicked(e);
    }
    if(event_code == LV_EVENT_LONG_PRESSED) {
        OnYellowCardRightLongPressed(e);
    }
}

void ui_event_ButtonRRight(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        OnRedCardRightClicked(e);
    }
    if(event_code == LV_EVENT_LONG_PRESSED) {
        OnRedCardRightLongPressed(e);
    }
}

void ui_event_ButtonBRight(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        OnBlackCardRightClicked(e);
    }
    if(event_code == LV_EVENT_LONG_PRESSED) {
        OnBlackCardRightLongPressed(e);
    }
}

void ui_event_ButtonUW2F(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        OnUW2FClicked(e);
    }
    if(event_code == LV_EVENT_LONG_PRESSED) {
        OnUW2FLongPressed(e);
    }
}

void ui_event_ButtonPRIO(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        OnPrioClicked(e);
    }
    if(event_code == LV_EVENT_LONG_PRESSED) {
        OnPrioLongPressed(e);
    }
}

void ui_event_ButtonUndoUW2FTimerReset(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        OnUNDOUW2FTimerResetClicked(e);
    }
}

// build funtions

void ui_Cards_Screen_screen_init(void)
{
    ui_Cards_Screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Cards_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButton4 = lv_imgbtn_create(ui_Cards_Screen);
    lv_imgbtn_set_src(ui_ImgButton4, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_icons_icon_home_png, NULL);
    lv_obj_set_width(ui_ImgButton4, 40);
    lv_obj_set_height(ui_ImgButton4, 40);
    lv_obj_set_x(ui_ImgButton4, 3);
    lv_obj_set_y(ui_ImgButton4, 0);
    lv_obj_set_align(ui_ImgButton4, LV_ALIGN_BOTTOM_LEFT);

    ui_Container2 = lv_obj_create(ui_Cards_Screen);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 100);
    lv_obj_set_height(ui_Container2, 180);
    lv_obj_set_x(ui_Container2, 10);
    lv_obj_set_y(ui_Container2, -5);
    lv_obj_set_flex_flow(ui_Container2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container2, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonYLeft = lv_btn_create(ui_Container2);
    lv_obj_set_width(ui_ButtonYLeft, 80);
    lv_obj_set_height(ui_ButtonYLeft, 40);
    lv_obj_set_x(ui_ButtonYLeft, -57);
    lv_obj_set_y(ui_ButtonYLeft, -133);
    lv_obj_set_align(ui_ButtonYLeft, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonYLeft, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonYLeft, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label12 = lv_label_create(ui_ButtonYLeft);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "Y");

    ui_ButtonRLeft = lv_btn_create(ui_Container2);
    lv_obj_set_width(ui_ButtonRLeft, 80);
    lv_obj_set_height(ui_ButtonRLeft, 40);
    lv_obj_set_x(ui_ButtonRLeft, -57);
    lv_obj_set_y(ui_ButtonRLeft, -77);
    lv_obj_set_align(ui_ButtonRLeft, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonRLeft, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonRLeft, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label13 = lv_label_create(ui_ButtonRLeft);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "R");

    ui_ButtonBLeft = lv_btn_create(ui_Container2);
    lv_obj_set_width(ui_ButtonBLeft, 80);
    lv_obj_set_height(ui_ButtonBLeft, 40);
    lv_obj_set_x(ui_ButtonBLeft, -57);
    lv_obj_set_y(ui_ButtonBLeft, -15);
    lv_obj_set_align(ui_ButtonBLeft, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonBLeft, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonBLeft, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label14 = lv_label_create(ui_ButtonBLeft);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "B");

    ui_Container3 = lv_obj_create(ui_Cards_Screen);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, 100);
    lv_obj_set_height(ui_Container3, 180);
    lv_obj_set_x(ui_Container3, 10);
    lv_obj_set_y(ui_Container3, -5);
    lv_obj_set_align(ui_Container3, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_flex_flow(ui_Container3, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container3, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonYRight = lv_btn_create(ui_Container3);
    lv_obj_set_width(ui_ButtonYRight, 80);
    lv_obj_set_height(ui_ButtonYRight, 40);
    lv_obj_set_x(ui_ButtonYRight, -57);
    lv_obj_set_y(ui_ButtonYRight, -133);
    lv_obj_set_align(ui_ButtonYRight, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonYRight, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonYRight, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label15 = lv_label_create(ui_ButtonYRight);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "Y");

    ui_ButtonRRight = lv_btn_create(ui_Container3);
    lv_obj_set_width(ui_ButtonRRight, 80);
    lv_obj_set_height(ui_ButtonRRight, 40);
    lv_obj_set_x(ui_ButtonRRight, -57);
    lv_obj_set_y(ui_ButtonRRight, -77);
    lv_obj_set_align(ui_ButtonRRight, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonRRight, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonRRight, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label16 = lv_label_create(ui_ButtonRRight);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "R");

    ui_ButtonBRight = lv_btn_create(ui_Container3);
    lv_obj_set_width(ui_ButtonBRight, 80);
    lv_obj_set_height(ui_ButtonBRight, 40);
    lv_obj_set_x(ui_ButtonBRight, -57);
    lv_obj_set_y(ui_ButtonBRight, -15);
    lv_obj_set_align(ui_ButtonBRight, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonBRight, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonBRight, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label17 = lv_label_create(ui_ButtonBRight);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "B");

    ui_ButtonUW2F = lv_btn_create(ui_Cards_Screen);
    lv_obj_set_width(ui_ButtonUW2F, 100);
    lv_obj_set_height(ui_ButtonUW2F, 35);
    lv_obj_set_x(ui_ButtonUW2F, 0);
    lv_obj_set_y(ui_ButtonUW2F, 30);
    lv_obj_set_align(ui_ButtonUW2F, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonUW2F, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonUW2F, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label18 = lv_label_create(ui_ButtonUW2F);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "UW2F");

    ui_ButtonPRIO = lv_btn_create(ui_Cards_Screen);
    lv_obj_set_width(ui_ButtonPRIO, 100);
    lv_obj_set_height(ui_ButtonPRIO, 35);
    lv_obj_set_x(ui_ButtonPRIO, 0);
    lv_obj_set_y(ui_ButtonPRIO, 75);
    lv_obj_set_align(ui_ButtonPRIO, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonPRIO, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonPRIO, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label19 = lv_label_create(ui_ButtonPRIO);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "PRIO");

    ui_ButtonUndoUW2FTimerReset = lv_btn_create(ui_Cards_Screen);
    lv_obj_set_width(ui_ButtonUndoUW2FTimerReset, 100);
    lv_obj_set_height(ui_ButtonUndoUW2FTimerReset, 35);
    lv_obj_set_x(ui_ButtonUndoUW2FTimerReset, 0);
    lv_obj_set_y(ui_ButtonUndoUW2FTimerReset, 125);
    lv_obj_set_align(ui_ButtonUndoUW2FTimerReset, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonUndoUW2FTimerReset, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonUndoUW2FTimerReset, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label20 = lv_label_create(ui_ButtonUndoUW2FTimerReset);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "UWF Timer");

    lv_obj_add_event_cb(ui_ImgButton4, ui_event_ImgButton4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonYLeft, ui_event_ButtonYLeft, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonRLeft, ui_event_ButtonRLeft, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonBLeft, ui_event_ButtonBLeft, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonYRight, ui_event_ButtonYRight, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonRRight, ui_event_ButtonRRight, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonBRight, ui_event_ButtonBRight, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonUW2F, ui_event_ButtonUW2F, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonPRIO, ui_event_ButtonPRIO, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonUndoUW2FTimerReset, ui_event_ButtonUndoUW2FTimerReset, LV_EVENT_ALL, NULL);

}

void ui_Cards_Screen_screen_destroy(void)
{
    if(ui_Cards_Screen) lv_obj_del(ui_Cards_Screen);

    // NULL screen variables
    ui_Cards_Screen = NULL;
    ui_ImgButton4 = NULL;
    ui_Container2 = NULL;
    ui_ButtonYLeft = NULL;
    ui_Label12 = NULL;
    ui_ButtonRLeft = NULL;
    ui_Label13 = NULL;
    ui_ButtonBLeft = NULL;
    ui_Label14 = NULL;
    ui_Container3 = NULL;
    ui_ButtonYRight = NULL;
    ui_Label15 = NULL;
    ui_ButtonRRight = NULL;
    ui_Label16 = NULL;
    ui_ButtonBRight = NULL;
    ui_Label17 = NULL;
    ui_ButtonUW2F = NULL;
    ui_Label18 = NULL;
    ui_ButtonPRIO = NULL;
    ui_Label19 = NULL;
    ui_ButtonUndoUW2FTimerReset = NULL;
    ui_Label20 = NULL;

}
