// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: RemoteControl

#include "ui.h"

lv_obj_t * ui_Central_Screen = NULL;
lv_obj_t * ui_ContainerMainTopLeft = NULL;
lv_obj_t * ui_ButtonLeftScorePlus = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_ContaineMainTopRight = NULL;
lv_obj_t * ui_ButtonRightScorePlus = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_ButtonStartStop = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_ButtonNextPause = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_ButtonReset = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_ImgButton2 = NULL;
lv_obj_t * ui_ImgButton3 = NULL;
lv_obj_t * ui_ImgButton7 = NULL;
lv_obj_t * ui_LabelPisteID = NULL;
// event funtions
void ui_event_Central_Screen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Cards_Screen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Cards_Screen_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Basic_Settings_Screen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Basic_Settings_Screen_screen_init);
    }
}

void ui_event_ButtonLeftScorePlus(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        OnLeftScorePlusLongPressed(e);
    }
    if(event_code == LV_EVENT_SHORT_CLICKED) {
        OnLeftScorePlusClicked(e);
    }
}

void ui_event_ButtonRightScorePlus(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        OnRightScorePlusLongPressed(e);
    }
    if(event_code == LV_EVENT_SHORT_CLICKED) {
        OnRightScorePlusClicked(e);
    }
}

void ui_event_ButtonStartStop(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        OnStartStopClicked(e);
    }
}

void ui_event_ButtonNextPause(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        OnNextPauseLongpressed(e);
    }
}

void ui_event_ButtonReset(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        OnResetClicked(e);
    }
    if(event_code == LV_EVENT_LONG_PRESSED) {
        OnResetLongPressed(e);
    }
}

void ui_event_ImgButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Cards_Screen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Cards_Screen_screen_init);
    }
}

void ui_event_ImgButton3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Cyrano_Screen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Cyrano_Screen_screen_init);
    }
}

void ui_event_ImgButton7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Basic_Settings_Screen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Basic_Settings_Screen_screen_init);
    }
}

// build funtions

void ui_Central_Screen_screen_init(void)
{
    ui_Central_Screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Central_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerMainTopLeft = lv_obj_create(ui_Central_Screen);
    lv_obj_remove_style_all(ui_ContainerMainTopLeft);
    lv_obj_set_width(ui_ContainerMainTopLeft, 100);
    lv_obj_set_height(ui_ContainerMainTopLeft, 120);
    lv_obj_clear_flag(ui_ContainerMainTopLeft, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonLeftScorePlus = lv_btn_create(ui_ContainerMainTopLeft);
    lv_obj_set_width(ui_ButtonLeftScorePlus, 80);
    lv_obj_set_height(ui_ButtonLeftScorePlus, 80);
    lv_obj_set_x(ui_ButtonLeftScorePlus, 10);
    lv_obj_set_y(ui_ButtonLeftScorePlus, 0);
    lv_obj_set_align(ui_ButtonLeftScorePlus, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonLeftScorePlus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonLeftScorePlus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_ButtonLeftScorePlus);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "+");

    ui_ContaineMainTopRight = lv_obj_create(ui_Central_Screen);
    lv_obj_remove_style_all(ui_ContaineMainTopRight);
    lv_obj_set_width(ui_ContaineMainTopRight, 100);
    lv_obj_set_height(ui_ContaineMainTopRight, 120);
    lv_obj_set_align(ui_ContaineMainTopRight, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_ContaineMainTopRight, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonRightScorePlus = lv_btn_create(ui_ContaineMainTopRight);
    lv_obj_set_width(ui_ButtonRightScorePlus, 80);
    lv_obj_set_height(ui_ButtonRightScorePlus, 80);
    lv_obj_set_x(ui_ButtonRightScorePlus, -10);
    lv_obj_set_y(ui_ButtonRightScorePlus, 0);
    lv_obj_set_align(ui_ButtonRightScorePlus, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonRightScorePlus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonRightScorePlus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_ButtonRightScorePlus);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "+");

    ui_ButtonStartStop = lv_btn_create(ui_Central_Screen);
    lv_obj_set_width(ui_ButtonStartStop, 150);
    lv_obj_set_height(ui_ButtonStartStop, 80);
    lv_obj_set_x(ui_ButtonStartStop, 0);
    lv_obj_set_y(ui_ButtonStartStop, -47);
    lv_obj_set_align(ui_ButtonStartStop, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonStartStop, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonStartStop,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_ButtonStartStop);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 0);
    lv_obj_set_y(ui_Label5, -15);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Start  / Stop");

    ui_ButtonNextPause = lv_btn_create(ui_Central_Screen);
    lv_obj_set_width(ui_ButtonNextPause, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_ButtonNextPause, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_ButtonNextPause, 5);
    lv_obj_set_y(ui_ButtonNextPause, 36);
    lv_obj_set_align(ui_ButtonNextPause, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonNextPause, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonNextPause, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label6 = lv_label_create(ui_ButtonNextPause);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "NEXT / PAUSE");

    ui_ButtonReset = lv_btn_create(ui_Central_Screen);
    lv_obj_set_width(ui_ButtonReset, 100);
    lv_obj_set_height(ui_ButtonReset, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_ButtonReset, 0);
    lv_obj_set_y(ui_ButtonReset, 87);
    lv_obj_set_align(ui_ButtonReset, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonReset, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonReset, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label7 = lv_label_create(ui_ButtonReset);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "RESET");

    ui_ImgButton2 = lv_imgbtn_create(ui_Central_Screen);
    lv_imgbtn_set_src(ui_ImgButton2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_icons_icon_next_png, NULL);
    lv_obj_set_width(ui_ImgButton2, 40);
    lv_obj_set_height(ui_ImgButton2, 40);
    lv_obj_set_x(ui_ImgButton2, 94);
    lv_obj_set_y(ui_ImgButton2, 130);
    lv_obj_set_align(ui_ImgButton2, LV_ALIGN_CENTER);

    ui_ImgButton3 = lv_imgbtn_create(ui_Central_Screen);
    lv_imgbtn_set_src(ui_ImgButton3, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_icons_icon_prev_png, NULL);
    lv_obj_set_width(ui_ImgButton3, 40);
    lv_obj_set_height(ui_ImgButton3, 40);
    lv_obj_set_x(ui_ImgButton3, -96);
    lv_obj_set_y(ui_ImgButton3, 131);
    lv_obj_set_align(ui_ImgButton3, LV_ALIGN_CENTER);

    ui_ImgButton7 = lv_imgbtn_create(ui_Central_Screen);
    lv_imgbtn_set_src(ui_ImgButton7, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_icons_icon_settings_png, NULL);
    lv_obj_set_width(ui_ImgButton7, 40);
    lv_obj_set_height(ui_ImgButton7, 40);
    lv_obj_set_x(ui_ImgButton7, 0);
    lv_obj_set_y(ui_ImgButton7, 137);
    lv_obj_set_align(ui_ImgButton7, LV_ALIGN_CENTER);

    ui_LabelPisteID = lv_label_create(ui_Central_Screen);
    lv_obj_set_width(ui_LabelPisteID, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPisteID, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPisteID, 0);
    lv_obj_set_y(ui_LabelPisteID, -10);
    lv_obj_set_align(ui_LabelPisteID, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPisteID, "Piste 999");

    lv_obj_add_event_cb(ui_ButtonLeftScorePlus, ui_event_ButtonLeftScorePlus, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonRightScorePlus, ui_event_ButtonRightScorePlus, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonStartStop, ui_event_ButtonStartStop, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonNextPause, ui_event_ButtonNextPause, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonReset, ui_event_ButtonReset, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton2, ui_event_ImgButton2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton3, ui_event_ImgButton3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton7, ui_event_ImgButton7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Central_Screen, ui_event_Central_Screen, LV_EVENT_ALL, NULL);

}

void ui_Central_Screen_screen_destroy(void)
{
    if(ui_Central_Screen) lv_obj_del(ui_Central_Screen);

    // NULL screen variables
    ui_Central_Screen = NULL;
    ui_ContainerMainTopLeft = NULL;
    ui_ButtonLeftScorePlus = NULL;
    ui_Label1 = NULL;
    ui_ContaineMainTopRight = NULL;
    ui_ButtonRightScorePlus = NULL;
    ui_Label3 = NULL;
    ui_ButtonStartStop = NULL;
    ui_Label5 = NULL;
    ui_ButtonNextPause = NULL;
    ui_Label6 = NULL;
    ui_ButtonReset = NULL;
    ui_Label7 = NULL;
    ui_ImgButton2 = NULL;
    ui_ImgButton3 = NULL;
    ui_ImgButton7 = NULL;
    ui_LabelPisteID = NULL;

}
