// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: RemoteControl

#include "ui.h"

lv_obj_t * ui_Cyrano_Screen = NULL;
lv_obj_t * ui_ImgButton8 = NULL;
lv_obj_t * ui_ButtonNext = NULL;
lv_obj_t * ui_Label23 = NULL;
lv_obj_t * ui_ButtonPrev = NULL;
lv_obj_t * ui_Label22 = NULL;
lv_obj_t * ui_ButtonBegin = NULL;
lv_obj_t * ui_Label24 = NULL;
lv_obj_t * ui_ButtonEnd = NULL;
lv_obj_t * ui_Label25 = NULL;
lv_obj_t * ui_ButtonSwap = NULL;
lv_obj_t * ui_Label26 = NULL;
lv_obj_t * ui_ImgButton9 = NULL;
lv_obj_t * ui_ButtonSwapResLeft = NULL;
lv_obj_t * ui_Label27 = NULL;
lv_obj_t * ui_ButtonSwapResRight = NULL;
lv_obj_t * ui_Label28 = NULL;
// event funtions
void ui_event_ImgButton8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Central_Screen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Central_Screen_screen_init);
    }
}

void ui_event_ButtonNext(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        OnNextClicked(e);
    }
}

void ui_event_ButtonPrev(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        OnPrevClicked(e);
    }
}

void ui_event_ButtonBegin(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        OnBeginLongPressed(e);
    }
}

void ui_event_ButtonEnd(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        OnEndLongPressed(e);
    }
}

void ui_event_ButtonSwap(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        OnSwapClicked(e);
    }
}

void ui_event_ImgButton9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Central_Screen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Central_Screen_screen_init);
    }
}

void ui_event_ButtonSwapResLeft(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        OnResLClicked(e);
    }
}

void ui_event_ButtonSwapResRight(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        OnResRClicked(e);
    }
}

// build funtions

void ui_Cyrano_Screen_screen_init(void)
{
    ui_Cyrano_Screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Cyrano_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButton8 = lv_imgbtn_create(ui_Cyrano_Screen);
    lv_imgbtn_set_src(ui_ImgButton8, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_icons_icon_home_png, NULL);
    lv_obj_set_width(ui_ImgButton8, 40);
    lv_obj_set_height(ui_ImgButton8, 40);
    lv_obj_set_x(ui_ImgButton8, 2);
    lv_obj_set_y(ui_ImgButton8, -3);
    lv_obj_set_align(ui_ImgButton8, LV_ALIGN_BOTTOM_LEFT);

    ui_ButtonNext = lv_btn_create(ui_Cyrano_Screen);
    lv_obj_set_width(ui_ButtonNext, 100);
    lv_obj_set_height(ui_ButtonNext, 35);
    lv_obj_set_x(ui_ButtonNext, 61);
    lv_obj_set_y(ui_ButtonNext, -132);
    lv_obj_set_align(ui_ButtonNext, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonNext, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonNext, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label23 = lv_label_create(ui_ButtonNext);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "Next");

    ui_ButtonPrev = lv_btn_create(ui_Cyrano_Screen);
    lv_obj_set_width(ui_ButtonPrev, 100);
    lv_obj_set_height(ui_ButtonPrev, 35);
    lv_obj_set_x(ui_ButtonPrev, -65);
    lv_obj_set_y(ui_ButtonPrev, -131);
    lv_obj_set_align(ui_ButtonPrev, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonPrev, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonPrev, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label22 = lv_label_create(ui_ButtonPrev);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "Prev");

    ui_ButtonBegin = lv_btn_create(ui_Cyrano_Screen);
    lv_obj_set_width(ui_ButtonBegin, 100);
    lv_obj_set_height(ui_ButtonBegin, 35);
    lv_obj_set_x(ui_ButtonBegin, -6);
    lv_obj_set_y(ui_ButtonBegin, -58);
    lv_obj_set_align(ui_ButtonBegin, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonBegin, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonBegin, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label24 = lv_label_create(ui_ButtonBegin);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "Begin");

    ui_ButtonEnd = lv_btn_create(ui_Cyrano_Screen);
    lv_obj_set_width(ui_ButtonEnd, 100);
    lv_obj_set_height(ui_ButtonEnd, 35);
    lv_obj_set_x(ui_ButtonEnd, -7);
    lv_obj_set_y(ui_ButtonEnd, -8);
    lv_obj_set_align(ui_ButtonEnd, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonEnd, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonEnd, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label25 = lv_label_create(ui_ButtonEnd);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "End");

    ui_ButtonSwap = lv_btn_create(ui_Cyrano_Screen);
    lv_obj_set_width(ui_ButtonSwap, 100);
    lv_obj_set_height(ui_ButtonSwap, 35);
    lv_obj_set_x(ui_ButtonSwap, -2);
    lv_obj_set_y(ui_ButtonSwap, 112);
    lv_obj_set_align(ui_ButtonSwap, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonSwap, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonSwap, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label26 = lv_label_create(ui_ButtonSwap);
    lv_obj_set_width(ui_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label26, "Swap");

    ui_ImgButton9 = lv_imgbtn_create(ui_Cyrano_Screen);
    lv_imgbtn_set_src(ui_ImgButton9, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_icons_icon_next_png, NULL);
    lv_obj_set_width(ui_ImgButton9, 40);
    lv_obj_set_height(ui_ImgButton9, 40);
    lv_obj_set_x(ui_ImgButton9, 97);
    lv_obj_set_y(ui_ImgButton9, 137);
    lv_obj_set_align(ui_ImgButton9, LV_ALIGN_CENTER);

    ui_ButtonSwapResLeft = lv_btn_create(ui_Cyrano_Screen);
    lv_obj_set_width(ui_ButtonSwapResLeft, 47);
    lv_obj_set_height(ui_ButtonSwapResLeft, 35);
    lv_obj_set_x(ui_ButtonSwapResLeft, -85);
    lv_obj_set_y(ui_ButtonSwapResLeft, 55);
    lv_obj_set_align(ui_ButtonSwapResLeft, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonSwapResLeft, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonSwapResLeft, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label27 = lv_label_create(ui_ButtonSwapResLeft);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "ResL");

    ui_ButtonSwapResRight = lv_btn_create(ui_Cyrano_Screen);
    lv_obj_set_width(ui_ButtonSwapResRight, 47);
    lv_obj_set_height(ui_ButtonSwapResRight, 35);
    lv_obj_set_x(ui_ButtonSwapResRight, 85);
    lv_obj_set_y(ui_ButtonSwapResRight, 55);
    lv_obj_set_align(ui_ButtonSwapResRight, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonSwapResRight, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonSwapResRight, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label28 = lv_label_create(ui_ButtonSwapResRight);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label28, "ResR");

    lv_obj_add_event_cb(ui_ImgButton8, ui_event_ImgButton8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonNext, ui_event_ButtonNext, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonPrev, ui_event_ButtonPrev, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonBegin, ui_event_ButtonBegin, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonEnd, ui_event_ButtonEnd, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonSwap, ui_event_ButtonSwap, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton9, ui_event_ImgButton9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonSwapResLeft, ui_event_ButtonSwapResLeft, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonSwapResRight, ui_event_ButtonSwapResRight, LV_EVENT_ALL, NULL);

}

void ui_Cyrano_Screen_screen_destroy(void)
{
    if(ui_Cyrano_Screen) lv_obj_del(ui_Cyrano_Screen);

    // NULL screen variables
    ui_Cyrano_Screen = NULL;
    ui_ImgButton8 = NULL;
    ui_ButtonNext = NULL;
    ui_Label23 = NULL;
    ui_ButtonPrev = NULL;
    ui_Label22 = NULL;
    ui_ButtonBegin = NULL;
    ui_Label24 = NULL;
    ui_ButtonEnd = NULL;
    ui_Label25 = NULL;
    ui_ButtonSwap = NULL;
    ui_Label26 = NULL;
    ui_ImgButton9 = NULL;
    ui_ButtonSwapResLeft = NULL;
    ui_Label27 = NULL;
    ui_ButtonSwapResRight = NULL;
    ui_Label28 = NULL;

}
