// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: RemoteControl

#ifndef UI_COLOR_SCREEN_H
#define UI_COLOR_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Color_Screen
extern void ui_Color_Screen_screen_init(void);
extern void ui_Color_Screen_screen_destroy(void);
extern lv_obj_t * ui_Color_Screen;
extern void ui_event_ImgButton18(lv_event_t * e);
extern lv_obj_t * ui_ImgButton18;
extern lv_obj_t * ui_Colorwheel1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

