// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: RemoteControl

#ifndef UI_CYRANO_SCREEN_H
#define UI_CYRANO_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Cyrano_Screen
extern void ui_Cyrano_Screen_screen_init(void);
extern void ui_Cyrano_Screen_screen_destroy(void);
extern lv_obj_t * ui_Cyrano_Screen;
extern void ui_event_ImgButton8(lv_event_t * e);
extern lv_obj_t * ui_ImgButton8;
extern void ui_event_ButtonNext(lv_event_t * e);
extern lv_obj_t * ui_ButtonNext;
extern lv_obj_t * ui_Label23;
extern void ui_event_ButtonPrev(lv_event_t * e);
extern lv_obj_t * ui_ButtonPrev;
extern lv_obj_t * ui_Label22;
extern void ui_event_ButtonBegin(lv_event_t * e);
extern lv_obj_t * ui_ButtonBegin;
extern lv_obj_t * ui_Label24;
extern void ui_event_ButtonEnd(lv_event_t * e);
extern lv_obj_t * ui_ButtonEnd;
extern lv_obj_t * ui_Label25;
extern void ui_event_ButtonSwap(lv_event_t * e);
extern lv_obj_t * ui_ButtonSwap;
extern lv_obj_t * ui_Label26;
extern void ui_event_ImgButton9(lv_event_t * e);
extern lv_obj_t * ui_ImgButton9;
extern void ui_event_ButtonSwapResLeft(lv_event_t * e);
extern lv_obj_t * ui_ButtonSwapResLeft;
extern lv_obj_t * ui_Label27;
extern void ui_event_ButtonSwapResRight(lv_event_t * e);
extern lv_obj_t * ui_ButtonSwapResRight;
extern lv_obj_t * ui_Label28;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

