// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: RemoteControl

#ifndef UI_CENTRAL_SCREEN_H
#define UI_CENTRAL_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Central_Screen
extern void ui_Central_Screen_screen_init(void);
extern void ui_Central_Screen_screen_destroy(void);
extern void ui_event_Central_Screen(lv_event_t * e);
extern lv_obj_t * ui_Central_Screen;
extern lv_obj_t * ui_ContainerMainTopLeft;
extern void ui_event_ButtonLeftScorePlus(lv_event_t * e);
extern lv_obj_t * ui_ButtonLeftScorePlus;
extern lv_obj_t * ui_Label1;
extern void ui_event_ButtonLeftScoreMin(lv_event_t * e);
extern lv_obj_t * ui_ButtonLeftScoreMin;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_ContaineMainTopRight;
extern void ui_event_ButtonRightScorePlus(lv_event_t * e);
extern lv_obj_t * ui_ButtonRightScorePlus;
extern lv_obj_t * ui_Label3;
extern void ui_event_ButtonRightScoreMin(lv_event_t * e);
extern lv_obj_t * ui_ButtonRightScoreMin;
extern lv_obj_t * ui_Label4;
extern void ui_event_ButtonStartStop(lv_event_t * e);
extern lv_obj_t * ui_ButtonStartStop;
extern lv_obj_t * ui_Label5;
extern void ui_event_ButtonNextPause(lv_event_t * e);
extern lv_obj_t * ui_ButtonNextPause;
extern lv_obj_t * ui_Label6;
extern void ui_event_ButtonReset(lv_event_t * e);
extern lv_obj_t * ui_ButtonReset;
extern lv_obj_t * ui_Label7;
extern void ui_event_ImgButton2(lv_event_t * e);
extern lv_obj_t * ui_ImgButton2;
extern lv_obj_t * ui_ImgButton3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

