// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: RemoteControl

#include <stdio.h>
#include "ui.h"

extern bool sendUDP32(uint32_t value);

void OnLeftScorePlusClicked(lv_event_t * e)
{
	// Your code here
	sendUDP32(0x06000005);
}

void OnScoreLeftMinClicked(lv_event_t * e)
{
	// Your code here
	sendUDP32(0x06000006);
}

void OnStartStopClicked(lv_event_t * e)
{
	// Your code here
	printf("The user clicked START/STOP\n");
	sendUDP32(0x06000011);
}

void OnSwipeLeft(lv_event_t * e)
{
	// Your code here
}

void OnResetClicked(lv_event_t * e)
{
	// Your code here
}

void OnResetLongPressed(lv_event_t * e)
{
	// Your code here
	sendUDP32(0x06000003);
}

void OnRightScorePlusClicked(lv_event_t * e)
{
	// Your code here
	sendUDP32(0x06000007);
}

void OnRightScoreMinClicked(lv_event_t * e)
{
	// Your code here
	sendUDP32(0x06000008);
}


void OnNextPauseLongpressed(lv_event_t * e)
{
	// Your code here
	sendUDP32(0x06000021);
}

void OnCycleWeaponClicked(lv_event_t * e)
{
	// Your code here
	sendUDP32(0x06000012);
}

void OnCycleMatchTypeClicked(lv_event_t * e)
{
	// Your code here
	sendUDP32(0x0600000a);
}

void OnCycleIntensityClicked(lv_event_t * e)
{
	// Your code here
	sendUDP32(0x06000030);
}

void OnYellowCardLeftClicked(lv_event_t * e)
{
	// Your code here
	sendUDP32(0x06000013);
}

void OnRedCardLeftClicked(lv_event_t * e)
{
	// Your code here
	sendUDP32(0x06000015);
}

void OnBlackCardLeftClicked(lv_event_t * e)
{
	// Your code here
	sendUDP32(0x06000051);
	
}

void OnYellowCardRightClicked(lv_event_t * e)
{
	// Your code here
	sendUDP32(0x06000014);
}

void OnRedCardRightClicked(lv_event_t * e)
{
	// Your code here
	sendUDP32(0x06000016);
}

void OnBlackCardRightClicked(lv_event_t * e)
{
	// Your code here
	sendUDP32(0x06000050);
	
}

void OnUW2FClicked(lv_event_t * e)
{
	// Your code here
	sendUDP32(0x06000017);
	
}

void OnPrioClicked(lv_event_t * e)
{
	// Your code here
	sendUDP32(0x06000010);
}

void OnRedCardLeftLongPressed(lv_event_t * e)
{
	// Your code here
	sendUDP32(0x0600ff15);
}

void OnBlackCardLeftLongPressed(lv_event_t * e)
{
	// Your code here
	sendUDP32(0x0600ff51);
}

void OnYellowCardRightLongPressed(lv_event_t * e)
{
	// Your code here
	sendUDP32(0x0600ff14);
}

void OnBlackCardRightLongPressed(lv_event_t * e)
{
	// Your code here
	sendUDP32(0x0600ff50);
}

void OnUW2FLongPressed(lv_event_t * e)
{
	// Your code here
	sendUDP32(0x0600ff17);
}

void OnPrioLongPressed(lv_event_t * e)
{
	// Your code here
}

void OnYellowCardLeftLongPressed(lv_event_t * e)
{
	// Your code here
	sendUDP32(0x0600ff13);
}

void OnRedCardRightLongPressed(lv_event_t * e)
{
	// Your code here
	sendUDP32(0x0600ff16);
}
