// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: RemoteControl

#include "../backlight.h"
#include "../wifi_udp.h"
#include "msgbox.h"
#include "ui.h"
#include <ctype.h>
#include <stdio.h>
#include <string.h>

extern bool sendUDP32(uint32_t value);

void OnLeftScorePlusClicked(lv_event_t *e) {
  // Your code here
  sendUDP32(0x06000005);
}

void OnScoreLeftMinClicked(lv_event_t *e) {
  // Your code here
  sendUDP32(0x06000006);
}

void OnStartStopClicked(lv_event_t *e) {
  // Your code here
  sendUDP32(0x06000011);
}

void OnSwipeLeft(lv_event_t *e) {
  // Your code here
}

void OnResetClicked(lv_event_t *e) {
  // Your code here
}

void OnResetLongPressed(lv_event_t *e) {
  // Your code here
  sendUDP32(0x06000003);
}

void OnRightScorePlusClicked(lv_event_t *e) {
  // Your code here
  sendUDP32(0x06000007);
}

void OnRightScoreMinClicked(lv_event_t *e) {
  // Your code here
  sendUDP32(0x06000008);
}

void OnNextPauseLongpressed(lv_event_t *e) {
  // Your code here
  sendUDP32(0x06000021);
}

void OnCycleWeaponClicked(lv_event_t *e) {
  // Your code here
  sendUDP32(0x06000012);
}

void OnCycleMatchTypeClicked(lv_event_t *e) {
  // Your code here
  sendUDP32(0x0600000a);
}

void OnCycleIntensityClicked(lv_event_t *e) {
  // Your code here
  sendUDP32(0x06000030);
}

void OnYellowCardLeftClicked(lv_event_t *e) {
  // Your code here
  sendUDP32(0x06000013);
}

void OnRedCardLeftClicked(lv_event_t *e) {
  // Your code here
  sendUDP32(0x06000015);
}

void OnBlackCardLeftClicked(lv_event_t *e) {
  // Your code here
  sendUDP32(0x06000051);
}

void OnYellowCardRightClicked(lv_event_t *e) {
  // Your code here
  sendUDP32(0x06000014);
}

void OnRedCardRightClicked(lv_event_t *e) {
  // Your code here
  sendUDP32(0x06000016);
}

void OnBlackCardRightClicked(lv_event_t *e) {
  // Your code here
  sendUDP32(0x06000050);
}

void OnUW2FClicked(lv_event_t *e) {
  // Your code here
  sendUDP32(0x06000017);
}

void OnPrioClicked(lv_event_t *e) {
  // Your code here
  sendUDP32(0x06000010);
}

void OnRedCardLeftLongPressed(lv_event_t *e) {
  // Your code here
  sendUDP32(0x0600ff15);
}

void OnBlackCardLeftLongPressed(lv_event_t *e) {
  // Your code here
  sendUDP32(0x0600ff51);
}

void OnYellowCardRightLongPressed(lv_event_t *e) {
  // Your code here
  sendUDP32(0x0600ff14);
}

void OnBlackCardRightLongPressed(lv_event_t *e) {
  // Your code here
  sendUDP32(0x0600ff50);
}

void OnUW2FLongPressed(lv_event_t *e) {
  // Your code here
  sendUDP32(0x0600ff17);
}

void OnPrioLongPressed(lv_event_t *e) {
  // Your code here
}

void OnYellowCardLeftLongPressed(lv_event_t *e) {
  // Your code here
  sendUDP32(0x0600ff13);
}

void OnRedCardRightLongPressed(lv_event_t *e) {
  // Your code here
  sendUDP32(0x0600ff16);
}

void OnUNDOUW2FTimerResetClicked(lv_event_t *e) {
  // Your code here
  sendUDP32(0x06000019);
}

extern int PisteNr;
void OnPisteIDChanged(lv_event_t *e) {
  // Your code here

  const char *pisteValue = lv_textarea_get_text(ui_TextAreaPisteNr);
  PisteNr = atoi(pisteValue);
  lv_label_set_text_fmt(ui_LabelPisteID, "Piste %s", pisteValue);
  printf("The user changed the piste to %s (int: %d)\n", pisteValue, PisteNr);
  SetPiste(PisteNr);
}

void OnNextClicked(lv_event_t *e) {
  // Your code here
  sendUDP32(0x06000101);
}

void OnPrevClicked(lv_event_t *e) {
  // Your code here
  sendUDP32(0x06000102);
}

void OnBeginLongPressed(lv_event_t *e) {
  // Your code here
  sendUDP32(0x06000103);
}

void OnEndLongPressed(lv_event_t *e) {
  // Your code here
  sendUDP32(0x06000104);
}

void OnSwapClicked(lv_event_t *e) {
  // Your code here
  sendUDP32(0x0600001a);
}

void OnResLClicked(lv_event_t *e) {
  // Your code here
  sendUDP32(0x0600001);
}

void OnResRClicked(lv_event_t *e) {
  // Your code here
  sendUDP32(0x0600001c);
}

void OnLeftScorePlusLongPressed(lv_event_t *e) {
  // Your code here
  sendUDP32(0x06000006);
}

void OnRightScorePlusLongPressed(lv_event_t *e) {
  // Your code here
  sendUDP32(0x06000008);
}

// Prevent OnTimerTextChanged from running during programmatic text updates
static bool timerFormatting = false;

// Restore : and . if deleted
void OnTimerTextChanged(lv_event_t *e) {
  // Prevent recursive calls and external programmatic updates
  if (timerFormatting)
    return;

  lv_obj_t *textarea = lv_event_get_target(e);
  const char *text = lv_textarea_get_text(textarea);
  int len = strlen(text);

  // Check if separators are missing
  bool has_colon = strchr(text, ':') != NULL;
  bool has_dot = strchr(text, '.') != NULL;

  if (has_colon && has_dot)
    return; // Format is fine

  // Make a copy to work with
  char fixed[10];
  strncpy(fixed, text, sizeof(fixed) - 1);
  fixed[sizeof(fixed) - 1] = '\0';

  timerFormatting = true;

  // Restore missing separators at their expected positions
  // Format: M:SS.HH (positions: 0:1 2 3.4 5 6)
  if (!has_colon && len >= 1) {
    // Insert : after position 1
    lv_textarea_set_cursor_pos(textarea, 1);
    lv_textarea_add_char(textarea, ':');
  }

  // Re-get text after potential colon insertion
  text = lv_textarea_get_text(textarea);
  len = strlen(text);

  if (!has_dot && len >= 4) {
    // Insert . after position 4
    lv_textarea_set_cursor_pos(textarea, 4);
    lv_textarea_add_char(textarea, '.');
  }

  // Move cursor to end
  lv_textarea_set_cursor_pos(textarea, LV_TEXTAREA_CURSOR_LAST);

  timerFormatting = false;
}

#define UI_SET_MINUTES 0x06000040
#define UI_SET_SECONDS 0x06000041
#define UI_SET_HUNDREDS 0x06000042

void OnNewTimeEntered(lv_event_t *e) {
  // Get the time text from textarea
  const char *timeText = lv_textarea_get_text(ui_TextAreaTimer);

  // Parse format M:SS.HH
  int minutes = 0, seconds = 0, hundredths = 0;

  // Find positions of separators
  const char *colon = strchr(timeText, ':');
  const char *dot = strchr(timeText, '.');

  if (colon && dot) {
    // Extract minutes (before :)
    minutes = atoi(timeText);

    // Extract seconds (between : and .)
    seconds = atoi(colon + 1);

    // Extract hundredths (after .)
    hundredths = atoi(dot + 1);

    // Send each value via UDP
    sendUDP32(UI_SET_MINUTES | (minutes << 8 & 0xFF00));
    sendUDP32(UI_SET_SECONDS | (seconds << 8 & 0xFF00));
    sendUDP32(UI_SET_HUNDREDS | (hundredths << 8 & 0xFF00));

    printf("Time set: %d:%02d.%02d\n", minutes, seconds, hundredths);
  }
}

void OnDefaultBrightnessFocussed(lv_event_t *e) {
  // Associate keyboard with Default Brightness textarea
  lv_keyboard_set_textarea(ui_Keyboard4, ui_TextAreaDefaultBrightness);
  printf("Default brightness is now actively edited\n");
}

void OnIdleBrightnessFocussed(lv_event_t *e) {
  // Associate keyboard with Idle Brightness textarea
  lv_keyboard_set_textarea(ui_Keyboard4, ui_TextAreaIdleBrightness);
  printf("Idle brightness is now actively edited\n");
}

void OnTimeToIdleFocussed(lv_event_t *e) {
  // Associate keyboard with Time to Idle textarea
  lv_keyboard_set_textarea(ui_Keyboard4, ui_TextAreaTimeToIdle);
  printf("Time to idle is now actively edited\n");
}

void OnPowerSettingKeyboardEnter(lv_event_t *e) {
  // Get the keyboard object from the event
  lv_obj_t *keyboard = lv_event_get_target(e);

  // Get the textarea that the keyboard is associated with
  lv_obj_t *activeTextarea = lv_keyboard_get_textarea(keyboard);

  if (activeTextarea == NULL) {
    printf("No textarea associated with keyboard\n");
    return;
  }

  // Get the text from the active textarea
  const char *valueText = lv_textarea_get_text(activeTextarea);
  int value = atoi(valueText);

  // Determine which textarea is active and call the appropriate setter
  if (activeTextarea == ui_TextAreaDefaultBrightness) {
    setDefaultBrightness((uint8_t)value);
    printf("Default brightness set to %d\n", value);
  } else if (activeTextarea == ui_TextAreaIdleBrightness) {
    setIdleBrightness((uint8_t)value);
    printf("Idle brightness set to %d\n", value);
  } else if (activeTextarea == ui_TextAreaTimeToIdle) {
    // Convert seconds to milliseconds
    uint32_t timeoutMs = (uint32_t)value * 1000;
    setBacklightTimeout(timeoutMs);
    printf("Backlight timeout set to %d seconds\n", value);
  } else {
    printf("Unknown textarea\n");
  }
}
#include "../fpa_protocol.h"
void OnCentralScreenLoading(lv_event_t *e) {
  // Your code here
  FPA::GlobalState local;

  FPA::lockState();
  local = FPA::getState();
  FPA::unlockState();
  lv_label_set_text(ui_Label1, local.score.scoreLeft);
  lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
  lv_label_set_text(ui_Label3, local.score.scoreRight);
}

void OnTimeScreenLoading(lv_event_t *e) {
  // Your code here
  FPA::GlobalState local;

  FPA::lockState();
  local = FPA::getState();
  FPA::unlockState();
  timerFormatting = true;
  lv_textarea_set_text(ui_TextAreaTimer, local.time.value);
  timerFormatting = false;
}

static void makeVertical(const char *src, char *dst, size_t dstSize) {
  size_t out = 0;
  for (size_t i = 0; src[i] != '\0' && out + 2 < dstSize; i++) {
    dst[out++] = (char)toupper((unsigned char)src[i]);
    dst[out++] = '\n';
  }
  dst[out] = '\0';
}

void OnLoadingCyranoScreen(lv_event_t *e) {
  // Your code here
  FPA::GlobalState local;

  FPA::lockState();
  local = FPA::getState();
  FPA::unlockState();

  char leftVert[sizeof(local.left.name) * 2 + 1];
  char rightVert[sizeof(local.right.name) * 2 + 1];
  makeVertical(local.left.name, leftVert, sizeof(leftVert));
  makeVertical(local.right.name, rightVert, sizeof(rightVert));

  lv_label_set_text(ui_LabelLeftFencerName, leftVert);
  lv_label_set_text(ui_LabelRightFencerName, rightVert);
}
#include "version.h"

void OnConnectionScreenLoading(lv_event_t *e) {
  // Your code here
  lv_label_set_text(ui_LabelVersion, FIRMWARE_VERSION);
}

void OTARemoteClicked(lv_event_t *e) {
  // Your code here
  ui_toast("In your browser connect to:\nhttp://192.168.5.1/update");
}

void OnOTASoringMachineClicked(lv_event_t *e) {
  // Your code here
  sendUDP32(0x06030000);
  ui_toast("The scoring device is now waiting for firmware.\nBrowse "
           "to:http://192.168.4.1/update");
}

void OnSettingsSCoringMachineClicked(lv_event_t *e) {
  // Your code here
  sendUDP32(0x06020000);
  ui_toast("The scoring device is now waiting for settings.\nBrowse "
           "to:http://192.168.4.1/");
}
