// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: RemoteControl

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void OnLeftScorePlusLongPressed(lv_event_t * e);
void OnLeftScorePlusClicked(lv_event_t * e);
void OnRightScorePlusLongPressed(lv_event_t * e);
void OnRightScorePlusClicked(lv_event_t * e);
void OnStartStopClicked(lv_event_t * e);
void OnNextPauseLongpressed(lv_event_t * e);
void OnResetClicked(lv_event_t * e);
void OnResetLongPressed(lv_event_t * e);
void OnCycleWeaponClicked(lv_event_t * e);
void OnCycleMatchTypeClicked(lv_event_t * e);
void OnCycleIntensityClicked(lv_event_t * e);
void OnYellowCardLeftClicked(lv_event_t * e);
void OnYellowCardLeftLongPressed(lv_event_t * e);
void OnRedCardLeftClicked(lv_event_t * e);
void OnRedCardLeftLongPressed(lv_event_t * e);
void OnBlackCardLeftClicked(lv_event_t * e);
void OnBlackCardLeftLongPressed(lv_event_t * e);
void OnYellowCardRightClicked(lv_event_t * e);
void OnYellowCardRightLongPressed(lv_event_t * e);
void OnRedCardRightClicked(lv_event_t * e);
void OnRedCardRightLongPressed(lv_event_t * e);
void OnBlackCardRightClicked(lv_event_t * e);
void OnBlackCardRightLongPressed(lv_event_t * e);
void OnUW2FClicked(lv_event_t * e);
void OnUW2FLongPressed(lv_event_t * e);
void OnPrioClicked(lv_event_t * e);
void OnPrioLongPressed(lv_event_t * e);
void OnUNDOUW2FTimerResetClicked(lv_event_t * e);
void OnPisteIDChanged(lv_event_t * e);
void OnNextClicked(lv_event_t * e);
void OnPrevClicked(lv_event_t * e);
void OnBeginLongPressed(lv_event_t * e);
void OnEndLongPressed(lv_event_t * e);
void OnSwapClicked(lv_event_t * e);
void OnResLClicked(lv_event_t * e);
void OnResRClicked(lv_event_t * e);
void OnPowerSettingKeyboardEnter(lv_event_t * e);
void OnDefaultBrightnessFocussed(lv_event_t * e);
void OnIdleBrightnessFocussed(lv_event_t * e);
void OnTimeToIdleFocussed(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
