// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: RemoteControl

#ifndef UI_NO_CONNECTION_SCREEN_H
#define UI_NO_CONNECTION_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_No_Connection_Screen
extern void ui_No_Connection_Screen_screen_init(void);
extern void ui_No_Connection_Screen_screen_destroy(void);
extern lv_obj_t * ui_No_Connection_Screen;
extern lv_obj_t * ui_Spinner1;
extern lv_obj_t * ui_Label11;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

