// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: RemoteControl

#include "ui.h"

lv_obj_t * ui_No_Connection_Screen = NULL;
lv_obj_t * ui_Spinner1 = NULL;
lv_obj_t * ui_Label11 = NULL;
// event funtions

// build funtions

void ui_No_Connection_Screen_screen_init(void)
{
    ui_No_Connection_Screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_No_Connection_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Spinner1 = lv_spinner_create(ui_No_Connection_Screen, 1000, 90);
    lv_obj_set_width(ui_Spinner1, 80);
    lv_obj_set_height(ui_Spinner1, 80);
    lv_obj_set_x(ui_Spinner1, 6);
    lv_obj_set_y(ui_Spinner1, -49);
    lv_obj_set_align(ui_Spinner1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner1, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_Label11 = lv_label_create(ui_No_Connection_Screen);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, 4);
    lv_obj_set_y(ui_Label11, 39);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "Waiting for scoring device");

}

void ui_No_Connection_Screen_screen_destroy(void)
{
    if(ui_No_Connection_Screen) lv_obj_del(ui_No_Connection_Screen);

    // NULL screen variables
    ui_No_Connection_Screen = NULL;
    ui_Spinner1 = NULL;
    ui_Label11 = NULL;

}
