// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: RemoteControl

#include "ui.h"

lv_obj_t * ui_OTA_Screen = NULL;
lv_obj_t * ui_ImgButton15 = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_ButtonOTAScoringMachine = NULL;
lv_obj_t * ui_Label33 = NULL;
lv_obj_t * ui_ButtonSettingsScoringMachine = NULL;
lv_obj_t * ui_Label34 = NULL;
lv_obj_t * ui_Label36 = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_ButtonOTARemote = NULL;
lv_obj_t * ui_Label32 = NULL;
lv_obj_t * ui_Label35 = NULL;
// event funtions
void ui_event_ImgButton15(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Central_Screen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Central_Screen_screen_init);
    }
}

void ui_event_ButtonOTAScoringMachine(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        OnOTASoringMachineClicked(e);
    }
}

void ui_event_ButtonSettingsScoringMachine(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        OnSettingsSCoringMachineClicked(e);
    }
}

void ui_event_ButtonOTARemote(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        OTARemoteClicked(e);
    }
}

// build funtions

void ui_OTA_Screen_screen_init(void)
{
    ui_OTA_Screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_OTA_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButton15 = lv_imgbtn_create(ui_OTA_Screen);
    lv_imgbtn_set_src(ui_ImgButton15, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_icons_icon_home_png, NULL);
    lv_obj_set_width(ui_ImgButton15, 40);
    lv_obj_set_height(ui_ImgButton15, 40);
    lv_obj_set_x(ui_ImgButton15, 2);
    lv_obj_set_y(ui_ImgButton15, -3);
    lv_obj_set_align(ui_ImgButton15, LV_ALIGN_BOTTOM_LEFT);

    ui_Panel1 = lv_obj_create(ui_OTA_Screen);
    lv_obj_set_width(ui_Panel1, 173);
    lv_obj_set_height(ui_Panel1, 185);
    lv_obj_set_x(ui_Panel1, 9);
    lv_obj_set_y(ui_Panel1, 39);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonOTAScoringMachine = lv_btn_create(ui_Panel1);
    lv_obj_set_width(ui_ButtonOTAScoringMachine, 100);
    lv_obj_set_height(ui_ButtonOTAScoringMachine, 50);
    lv_obj_set_x(ui_ButtonOTAScoringMachine, -5);
    lv_obj_set_y(ui_ButtonOTAScoringMachine, -25);
    lv_obj_set_align(ui_ButtonOTAScoringMachine, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonOTAScoringMachine, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonOTAScoringMachine, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label33 = lv_label_create(ui_ButtonOTAScoringMachine);
    lv_obj_set_width(ui_Label33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label33, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label33, "OTA");

    ui_ButtonSettingsScoringMachine = lv_btn_create(ui_Panel1);
    lv_obj_set_width(ui_ButtonSettingsScoringMachine, 100);
    lv_obj_set_height(ui_ButtonSettingsScoringMachine, 50);
    lv_obj_set_x(ui_ButtonSettingsScoringMachine, -5);
    lv_obj_set_y(ui_ButtonSettingsScoringMachine, 47);
    lv_obj_set_align(ui_ButtonSettingsScoringMachine, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonSettingsScoringMachine, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonSettingsScoringMachine, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label34 = lv_label_create(ui_ButtonSettingsScoringMachine);
    lv_obj_set_width(ui_Label34, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label34, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label34, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label34, "Settings");

    ui_Label36 = lv_label_create(ui_OTA_Screen);
    lv_obj_set_width(ui_Label36, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label36, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label36, -10);
    lv_obj_set_y(ui_Label36, -32);
    lv_obj_set_align(ui_Label36, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label36, "Scoring Device");

    ui_Panel3 = lv_obj_create(ui_OTA_Screen);
    lv_obj_set_width(ui_Panel3, 168);
    lv_obj_set_height(ui_Panel3, 94);
    lv_obj_set_x(ui_Panel3, 8);
    lv_obj_set_y(ui_Panel3, -107);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonOTARemote = lv_btn_create(ui_Panel3);
    lv_obj_set_width(ui_ButtonOTARemote, 100);
    lv_obj_set_height(ui_ButtonOTARemote, 50);
    lv_obj_set_x(ui_ButtonOTARemote, -5);
    lv_obj_set_y(ui_ButtonOTARemote, 10);
    lv_obj_set_align(ui_ButtonOTARemote, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonOTARemote, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonOTARemote, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label32 = lv_label_create(ui_ButtonOTARemote);
    lv_obj_set_width(ui_Label32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label32, -1);
    lv_obj_set_y(ui_Label32, 0);
    lv_obj_set_align(ui_Label32, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label32, "OTA");

    ui_Label35 = lv_label_create(ui_OTA_Screen);
    lv_obj_set_width(ui_Label35, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label35, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label35, -6);
    lv_obj_set_y(ui_Label35, -134);
    lv_obj_set_align(ui_Label35, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label35, "Remote Control");

    lv_obj_add_event_cb(ui_ImgButton15, ui_event_ImgButton15, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonOTAScoringMachine, ui_event_ButtonOTAScoringMachine, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonSettingsScoringMachine, ui_event_ButtonSettingsScoringMachine, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonOTARemote, ui_event_ButtonOTARemote, LV_EVENT_ALL, NULL);

}

void ui_OTA_Screen_screen_destroy(void)
{
    if(ui_OTA_Screen) lv_obj_del(ui_OTA_Screen);

    // NULL screen variables
    ui_OTA_Screen = NULL;
    ui_ImgButton15 = NULL;
    ui_Panel1 = NULL;
    ui_ButtonOTAScoringMachine = NULL;
    ui_Label33 = NULL;
    ui_ButtonSettingsScoringMachine = NULL;
    ui_Label34 = NULL;
    ui_Label36 = NULL;
    ui_Panel3 = NULL;
    ui_ButtonOTARemote = NULL;
    ui_Label32 = NULL;
    ui_Label35 = NULL;

}
