// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: RemoteControl

#ifndef UI_OTA_SCREEN_H
#define UI_OTA_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_OTA_Screen
extern void ui_OTA_Screen_screen_init(void);
extern void ui_OTA_Screen_screen_destroy(void);
extern lv_obj_t * ui_OTA_Screen;
extern void ui_event_ImgButton15(lv_event_t * e);
extern lv_obj_t * ui_ImgButton15;
extern lv_obj_t * ui_Panel1;
extern void ui_event_ButtonOTAScoringMachine(lv_event_t * e);
extern lv_obj_t * ui_ButtonOTAScoringMachine;
extern lv_obj_t * ui_Label33;
extern void ui_event_ButtonSettingsScoringMachine(lv_event_t * e);
extern lv_obj_t * ui_ButtonSettingsScoringMachine;
extern lv_obj_t * ui_Label34;
extern lv_obj_t * ui_Label36;
extern lv_obj_t * ui_Panel3;
extern void ui_event_ButtonOTARemote(lv_event_t * e);
extern lv_obj_t * ui_ButtonOTARemote;
extern lv_obj_t * ui_Label32;
extern lv_obj_t * ui_Label35;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

