// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: RemoteControl

#include "ui.h"

lv_obj_t * ui_Power_Settings_Screen = NULL;
lv_obj_t * ui_ImgButton14 = NULL;
lv_obj_t * ui_Keyboard4 = NULL;
lv_obj_t * ui_Container4 = NULL;
lv_obj_t * ui_Label29 = NULL;
lv_obj_t * ui_TextAreaDefaultBrightness = NULL;
lv_obj_t * ui_Container5 = NULL;
lv_obj_t * ui_Label30 = NULL;
lv_obj_t * ui_TextAreaIdleBrightness = NULL;
lv_obj_t * ui_Container6 = NULL;
lv_obj_t * ui_Label31 = NULL;
lv_obj_t * ui_TextAreaTimeToIdle = NULL;
// event funtions
void ui_event_ImgButton14(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Central_Screen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Central_Screen_screen_init);
    }
}

void ui_event_Keyboard4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        OnPowerSettingKeyboardEnter(e);
    }
}

void ui_event_TextAreaDefaultBrightness(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        OnDefaultBrightnessFocussed(e);
    }
}

void ui_event_TextAreaIdleBrightness(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        OnIdleBrightnessFocussed(e);
    }
}

void ui_event_TextAreaTimeToIdle(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        OnTimeToIdleFocussed(e);
    }
}

// build funtions

void ui_Power_Settings_Screen_screen_init(void)
{
    ui_Power_Settings_Screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Power_Settings_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButton14 = lv_imgbtn_create(ui_Power_Settings_Screen);
    lv_imgbtn_set_src(ui_ImgButton14, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_icons_icon_home_png, NULL);
    lv_obj_set_width(ui_ImgButton14, 40);
    lv_obj_set_height(ui_ImgButton14, 40);
    lv_obj_set_align(ui_ImgButton14, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_ImgButton14, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags

    ui_Keyboard4 = lv_keyboard_create(ui_Power_Settings_Screen);
    lv_keyboard_set_mode(ui_Keyboard4, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_Keyboard4, 200);
    lv_obj_set_height(ui_Keyboard4, 120);
    lv_obj_set_x(ui_Keyboard4, 0);
    lv_obj_set_y(ui_Keyboard4, 46);
    lv_obj_set_align(ui_Keyboard4, LV_ALIGN_CENTER);

    ui_Container4 = lv_obj_create(ui_Power_Settings_Screen);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, 225);
    lv_obj_set_height(ui_Container4, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Container4, 5);
    lv_obj_set_y(ui_Container4, 0);
    lv_obj_set_flex_flow(ui_Container4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container4, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label29 = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label29, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label29, "Default Brightness");

    ui_TextAreaDefaultBrightness = lv_textarea_create(ui_Container4);
    lv_obj_set_width(ui_TextAreaDefaultBrightness, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextAreaDefaultBrightness, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextAreaDefaultBrightness, 41);
    lv_obj_set_y(ui_TextAreaDefaultBrightness, 28);
    lv_obj_set_align(ui_TextAreaDefaultBrightness, LV_ALIGN_BOTTOM_RIGHT);
    lv_textarea_set_accepted_chars(ui_TextAreaDefaultBrightness, "0123456789");
    lv_textarea_set_max_length(ui_TextAreaDefaultBrightness, 3);
    lv_textarea_set_text(ui_TextAreaDefaultBrightness, "80");
    lv_textarea_set_placeholder_text(ui_TextAreaDefaultBrightness, "Placeholder...");
    lv_textarea_set_one_line(ui_TextAreaDefaultBrightness, true);

    ui_Container5 = lv_obj_create(ui_Power_Settings_Screen);
    lv_obj_remove_style_all(ui_Container5);
    lv_obj_set_width(ui_Container5, 225);
    lv_obj_set_height(ui_Container5, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Container5, 5);
    lv_obj_set_y(ui_Container5, 50);
    lv_obj_set_flex_flow(ui_Container5, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container5, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label30 = lv_label_create(ui_Container5);
    lv_obj_set_width(ui_Label30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label30, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label30, "Idle Brightness");

    ui_TextAreaIdleBrightness = lv_textarea_create(ui_Container5);
    lv_obj_set_width(ui_TextAreaIdleBrightness, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextAreaIdleBrightness, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextAreaIdleBrightness, 41);
    lv_obj_set_y(ui_TextAreaIdleBrightness, 31);
    lv_obj_set_align(ui_TextAreaIdleBrightness, LV_ALIGN_BOTTOM_RIGHT);
    lv_textarea_set_accepted_chars(ui_TextAreaIdleBrightness, "0123456789");
    lv_textarea_set_max_length(ui_TextAreaIdleBrightness, 3);
    lv_textarea_set_text(ui_TextAreaIdleBrightness, "15");
    lv_textarea_set_placeholder_text(ui_TextAreaIdleBrightness, "Placeholder...");
    lv_textarea_set_one_line(ui_TextAreaIdleBrightness, true);

    ui_Container6 = lv_obj_create(ui_Power_Settings_Screen);
    lv_obj_remove_style_all(ui_Container6);
    lv_obj_set_width(ui_Container6, 225);
    lv_obj_set_height(ui_Container6, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Container6, 5);
    lv_obj_set_y(ui_Container6, 100);
    lv_obj_set_flex_flow(ui_Container6, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container6, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label31 = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_Label31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label31, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label31, "Time to Idle");

    ui_TextAreaTimeToIdle = lv_textarea_create(ui_Container6);
    lv_obj_set_width(ui_TextAreaTimeToIdle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextAreaTimeToIdle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextAreaTimeToIdle, 41);
    lv_obj_set_y(ui_TextAreaTimeToIdle, 28);
    lv_obj_set_align(ui_TextAreaTimeToIdle, LV_ALIGN_BOTTOM_RIGHT);
    lv_textarea_set_accepted_chars(ui_TextAreaTimeToIdle, "0123456789");
    lv_textarea_set_max_length(ui_TextAreaTimeToIdle, 3);
    lv_textarea_set_text(ui_TextAreaTimeToIdle, "20");
    lv_textarea_set_placeholder_text(ui_TextAreaTimeToIdle, "Placeholder...");
    lv_textarea_set_one_line(ui_TextAreaTimeToIdle, true);

    lv_obj_add_event_cb(ui_ImgButton14, ui_event_ImgButton14, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard4, ui_TextAreaDefaultBrightness);
    lv_obj_add_event_cb(ui_Keyboard4, ui_event_Keyboard4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextAreaDefaultBrightness, ui_event_TextAreaDefaultBrightness, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextAreaIdleBrightness, ui_event_TextAreaIdleBrightness, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextAreaTimeToIdle, ui_event_TextAreaTimeToIdle, LV_EVENT_ALL, NULL);

}

void ui_Power_Settings_Screen_screen_destroy(void)
{
    if(ui_Power_Settings_Screen) lv_obj_del(ui_Power_Settings_Screen);

    // NULL screen variables
    ui_Power_Settings_Screen = NULL;
    ui_ImgButton14 = NULL;
    ui_Keyboard4 = NULL;
    ui_Container4 = NULL;
    ui_Label29 = NULL;
    ui_TextAreaDefaultBrightness = NULL;
    ui_Container5 = NULL;
    ui_Label30 = NULL;
    ui_TextAreaIdleBrightness = NULL;
    ui_Container6 = NULL;
    ui_Label31 = NULL;
    ui_TextAreaTimeToIdle = NULL;

}
