// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: RemoteControl

#ifndef UI_POWER_SETTINGS_SCREEN_H
#define UI_POWER_SETTINGS_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Power_Settings_Screen
extern void ui_Power_Settings_Screen_screen_init(void);
extern void ui_Power_Settings_Screen_screen_destroy(void);
extern lv_obj_t * ui_Power_Settings_Screen;
extern void ui_event_ImgButton14(lv_event_t * e);
extern lv_obj_t * ui_ImgButton14;
extern void ui_event_Keyboard4(lv_event_t * e);
extern lv_obj_t * ui_Keyboard4;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_Label29;
extern void ui_event_TextAreaDefaultBrightness(lv_event_t * e);
extern lv_obj_t * ui_TextAreaDefaultBrightness;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_Label30;
extern void ui_event_TextAreaIdleBrightness(lv_event_t * e);
extern lv_obj_t * ui_TextAreaIdleBrightness;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_Label31;
extern void ui_event_TextAreaTimeToIdle(lv_event_t * e);
extern lv_obj_t * ui_TextAreaTimeToIdle;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

