// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: RemoteControl

#include "ui.h"

lv_obj_t * ui_SpecificSettingsScreen = NULL;
lv_obj_t * ui_TextAreaPisteNr = NULL;
lv_obj_t * ui_ImgButton5 = NULL;
lv_obj_t * ui_Keyboard2 = NULL;
lv_obj_t * ui_Label21 = NULL;
// event funtions
void ui_event_ImgButton5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Central_Screen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Central_Screen_screen_init);
    }
}

void ui_event_Keyboard2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        OnPisteIDChanged(e);
    }
}

// build funtions

void ui_SpecificSettingsScreen_screen_init(void)
{
    ui_SpecificSettingsScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SpecificSettingsScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TextAreaPisteNr = lv_textarea_create(ui_SpecificSettingsScreen);
    lv_obj_set_width(ui_TextAreaPisteNr, 52);
    lv_obj_set_height(ui_TextAreaPisteNr, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_TextAreaPisteNr, -78);
    lv_obj_set_y(ui_TextAreaPisteNr, -111);
    lv_obj_set_align(ui_TextAreaPisteNr, LV_ALIGN_CENTER);
    lv_textarea_set_accepted_chars(ui_TextAreaPisteNr, "0123456789");
    lv_textarea_set_max_length(ui_TextAreaPisteNr, 3);
    lv_textarea_set_text(ui_TextAreaPisteNr, "001");
    lv_textarea_set_placeholder_text(ui_TextAreaPisteNr, "Placeholder...");
    lv_textarea_set_one_line(ui_TextAreaPisteNr, true);

    ui_ImgButton5 = lv_imgbtn_create(ui_SpecificSettingsScreen);
    lv_imgbtn_set_src(ui_ImgButton5, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_icons_icon_home_png, NULL);
    lv_obj_set_width(ui_ImgButton5, 40);
    lv_obj_set_height(ui_ImgButton5, 40);
    lv_obj_set_x(ui_ImgButton5, 2);
    lv_obj_set_y(ui_ImgButton5, -3);
    lv_obj_set_align(ui_ImgButton5, LV_ALIGN_BOTTOM_LEFT);

    ui_Keyboard2 = lv_keyboard_create(ui_SpecificSettingsScreen);
    lv_keyboard_set_mode(ui_Keyboard2, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_Keyboard2, 240);
    lv_obj_set_height(ui_Keyboard2, 120);
    lv_obj_set_x(ui_Keyboard2, 0);
    lv_obj_set_y(ui_Keyboard2, 1);
    lv_obj_set_align(ui_Keyboard2, LV_ALIGN_CENTER);

    ui_Label21 = lv_label_create(ui_SpecificSettingsScreen);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label21, -52);
    lv_obj_set_y(ui_Label21, -143);
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "Piste number");

    lv_obj_add_event_cb(ui_ImgButton5, ui_event_ImgButton5, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard2, ui_TextAreaPisteNr);
    lv_obj_add_event_cb(ui_Keyboard2, ui_event_Keyboard2, LV_EVENT_ALL, NULL);

}

void ui_SpecificSettingsScreen_screen_destroy(void)
{
    if(ui_SpecificSettingsScreen) lv_obj_del(ui_SpecificSettingsScreen);

    // NULL screen variables
    ui_SpecificSettingsScreen = NULL;
    ui_TextAreaPisteNr = NULL;
    ui_ImgButton5 = NULL;
    ui_Keyboard2 = NULL;
    ui_Label21 = NULL;

}
