// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: RemoteControl

#ifndef UI_SPECIFICSETTINGSSCREEN_H
#define UI_SPECIFICSETTINGSSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SpecificSettingsScreen
extern void ui_SpecificSettingsScreen_screen_init(void);
extern void ui_SpecificSettingsScreen_screen_destroy(void);
extern lv_obj_t * ui_SpecificSettingsScreen;
extern lv_obj_t * ui_TextAreaPisteNr;
extern void ui_event_ImgButton5(lv_event_t * e);
extern lv_obj_t * ui_ImgButton5;
extern void ui_event_Keyboard2(lv_event_t * e);
extern lv_obj_t * ui_Keyboard2;
extern lv_obj_t * ui_Label21;
extern void ui_event_ImgButton13(lv_event_t * e);
extern lv_obj_t * ui_ImgButton13;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

