// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: RemoteControl

#ifndef UI_SET_TIME_SCREEN_H
#define UI_SET_TIME_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Set_Time_Screen
extern void ui_Set_Time_Screen_screen_init(void);
extern void ui_Set_Time_Screen_screen_destroy(void);
extern lv_obj_t * ui_Set_Time_Screen;
extern void ui_event_Keyboard1(lv_event_t * e);
extern lv_obj_t * ui_Keyboard1;
extern void ui_event_TextAreaTimer(lv_event_t * e);
extern lv_obj_t * ui_TextAreaTimer;
extern void ui_event_ImgButton12(lv_event_t * e);
extern lv_obj_t * ui_ImgButton12;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

