// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: RemoteControl

#include "ui.h"

lv_obj_t * ui_Set_Time_Screen = NULL;
lv_obj_t * ui_Keyboard1 = NULL;
lv_obj_t * ui_TextAreaTimer = NULL;
lv_obj_t * ui_ImgButton12 = NULL;
// event funtions
void ui_event_Keyboard1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        OnNewTimeEntered(e);
    }
}

void ui_event_ImgButton12(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Central_Screen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Central_Screen_screen_init);
    }
}

// build funtions

void ui_Set_Time_Screen_screen_init(void)
{
    ui_Set_Time_Screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Set_Time_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Keyboard1 = lv_keyboard_create(ui_Set_Time_Screen);
    lv_keyboard_set_mode(ui_Keyboard1, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_Keyboard1, 200);
    lv_obj_set_height(ui_Keyboard1, 120);
    lv_obj_set_x(ui_Keyboard1, -2);
    lv_obj_set_y(ui_Keyboard1, -11);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);

    ui_TextAreaTimer = lv_textarea_create(ui_Set_Time_Screen);
    lv_obj_set_width(ui_TextAreaTimer, 144);
    lv_obj_set_height(ui_TextAreaTimer, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_TextAreaTimer, 0);
    lv_obj_set_y(ui_TextAreaTimer, -125);
    lv_obj_set_align(ui_TextAreaTimer, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_TextAreaTimer, 7);
    lv_textarea_set_text(ui_TextAreaTimer, "2:33.30");
    lv_textarea_set_placeholder_text(ui_TextAreaTimer, "Placeholder...");
    lv_textarea_set_one_line(ui_TextAreaTimer, true);
    lv_obj_set_style_text_font(ui_TextAreaTimer, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton12 = lv_imgbtn_create(ui_Set_Time_Screen);
    lv_imgbtn_set_src(ui_ImgButton12, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_icons_icon_home_png, NULL);
    lv_obj_set_width(ui_ImgButton12, 40);
    lv_obj_set_height(ui_ImgButton12, 40);
    lv_obj_set_align(ui_ImgButton12, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_ImgButton12, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags

    lv_keyboard_set_textarea(ui_Keyboard1, ui_TextAreaTimer);
    lv_obj_add_event_cb(ui_Keyboard1, ui_event_Keyboard1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton12, ui_event_ImgButton12, LV_EVENT_ALL, NULL);

}

void ui_Set_Time_Screen_screen_destroy(void)
{
    if(ui_Set_Time_Screen) lv_obj_del(ui_Set_Time_Screen);

    // NULL screen variables
    ui_Set_Time_Screen = NULL;
    ui_Keyboard1 = NULL;
    ui_TextAreaTimer = NULL;
    ui_ImgButton12 = NULL;

}
